import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {modeAt,expiresAt,parseStorm,parseRadar,parseAlerts,parseForecast,collectWeather,assembleWeather} from './model.mjs';
const now=new Date('2026-10-09T14:00:00Z');
const config={stormId:'al092026',stormName:'Isaias',stormYear:2026,launchAt:'2026-10-09T14:00:00Z',modeOverride:'auto'};
const storm={id:'al092026',name:'Isaias',intensity:'105',pressure:'959',classification:'HU',latitude:'27.0N',longitude:'87.6W',movementDir:20,movementSpeed:15,lastUpdate:'2026-10-09T12:20:00Z',publicAdvisory:{advNum:'011a',issuance:'2026-10-09T12:00:00Z',url:'https://www.nhc.noaa.gov/text/MIATCPAT4.shtml'},forecastGraphics:{issuance:'2026-10-09T12:00:00Z',url:'https://www.nhc.noaa.gov/graphics_at4.shtml'}};
test('transition occurs at exactly launch + 48 hours, with explicit overrides',()=>{assert.equal(expiresAt(config),'2026-10-11T14:00:00.000Z');assert.equal(modeAt(config,new Date('2026-10-11T13:59:59.999Z')),'storm');assert.equal(modeAt(config,new Date('2026-10-11T14:00:00Z')),'regular');assert.equal(modeAt({...config,modeOverride:'storm'},new Date('2026-10-12')),'storm');assert.equal(modeAt({...config,modeOverride:'regular'},now),'regular');assert.equal(modeAt({...config,launchAt:null},now),'storm');});
test('NHC matches id, name, year and issue time; a reused AT4 slot is not enough',()=>{assert.equal(parseStorm(JSON.stringify({activeStorms:[storm]}),now,config).storm.windKt,105);assert.throws(()=>parseStorm(JSON.stringify({activeStorms:[{...storm,name:'Other'}]}),now,config),/identity/);assert.equal(parseStorm(JSON.stringify({activeStorms:[{...storm,id:'al102026'}]}),now,config).storm,null);assert.throws(()=>parseStorm(JSON.stringify({activeStorms:[{...storm,lastUpdate:'2026-10-10T12:00:00Z'}]}),now,config),/future/);assert.throws(()=>parseStorm(JSON.stringify({activeStorms:[{...storm,publicAdvisory:{...storm.publicAdvisory,url:'https://bad.example/slot'}}]}),now,config),/origin/);});
test('radar loop uses actual available instants and rejects future-only or single frame data',()=>{const times=['2026-10-09T13:40:00Z','2026-10-09T13:46:00Z','2026-10-09T13:52:00Z','2026-10-09T13:58:00Z','2026-10-10T13:58:00Z'];const r=parseRadar(`<Dimension name="time">${times.join(',')}</Dimension>`,now);assert.deepEqual(r.frames,times.slice(0,4));assert.equal(r.issuedAt,times[3]);assert.throws(()=>parseRadar('<Dimension name="time">2026-10-10T13:58:00Z</Dimension>',now),/unavailable/);});
const alert={id:'https://api.weather.gov/alerts/example',properties:{status:'Actual',messageType:'Alert',event:'Hurricane Warning',areaDesc:'Southern Jackson',geocode:{SAME:['028059']},sent:'2026-10-09T12:00:00Z',effective:'2026-10-09T12:00:00Z',expires:'2026-10-09T17:00:00Z'}};
test('alerts retain only actual active messages and valid empty feed is distinguishable',()=>{const p=parseAlerts(JSON.stringify({updated:now.toISOString(),features:[alert,{...alert,properties:{...alert.properties,status:'Test'}},{...alert,properties:{...alert.properties,expires:'2026-10-09T13:00:00Z'}}]}),now);assert.equal(p.alerts.length,1);assert.equal(p.alerts[0].mississippi,true);assert.equal(p.alerts[0].warning,true);assert.deepEqual(parseAlerts('{"features":[]}',now).alerts,[]);assert.throws(()=>parseAlerts('{}',now),/Invalid/);});
test('NWS uses updateTime and does not invent forecast rain chance',()=>{const p=parseForecast(JSON.stringify({properties:{updateTime:'2026-10-09T12:00:00Z',periods:[{endTime:'2026-10-10T12:00:00Z',temperature:80,probabilityOfPrecipitation:{value:null}}]}}),now);assert.equal(p.issuedAt,'2026-10-09T12:00:00.000Z');assert.equal(p.periods[0].rainChance,null);assert.throws(()=>parseForecast(JSON.stringify({properties:{updateTime:'2026-10-12T12:00:00Z',periods:[{}]}}),now),/future/);});
test('transient source failure preserves last good, delayed state and still-active warnings; recovery clears them',async()=>{const previous={id:'alerts',lastSuccess:'2026-10-09T13:59:00Z',data:parseAlerts(JSON.stringify({features:[alert]}),now)};const failed=await collectWeather({id:'alerts',kind:'alerts',url:'https://api.weather.gov/alerts/active'},previous,now,async()=>new Response('unavailable',{status:503}));assert.equal(failed.lastSuccess,previous.lastSuccess);assert.deepEqual(failed.data,previous.data);let data=assembleWeather([failed],now,config);assert.equal(data.sources.alerts.state,'delayed');assert.equal(data.sources.alerts.data.alerts.length,1);assert.equal(assembleWeather([failed],new Date('2026-10-09T18:00:00Z'),config).sources.alerts.data.alerts.length,0);const recovered=await collectWeather({id:'alerts',kind:'alerts',url:'https://api.weather.gov/alerts/active'},failed,now,async()=>Response.json({features:[]}));data=assembleWeather([recovered],now,config);assert.equal(data.sources.alerts.state,'current');assert.deepEqual(data.sources.alerts.data.alerts,[]);assert.equal(assembleWeather([],now,config).sources.alerts.state,'unavailable');});
test('browser source never reloads the page and broadcast templates are separate from ads/navigation',()=>{const code=readFileSync('src/assets/weather/client.mjs','utf8');assert.doesNotMatch(code,/location\.reload|location\.replace|setInterval[^\n]*location/);for(const path of ['src/weather-fixed.njk','src/weather-rotate.njk'])assert.match(readFileSync(path,'utf8'),/weather-shell/);const css=readFileSync('src/assets/weather/weather.css','utf8');assert.match(css,/width:1920px;height:1080px/);assert.match(css,/body\.broadcast \.masthead nav/);});

test('Pages cache honors independent source intervals, retains failures and recovers without clearing warnings',async()=>{
 const {weatherFromCache}=await import('./cache.mjs');const map=new Map();const cache={async match(r){return map.get(r.url)?.clone();},async put(r,v){map.set(r.url,v.clone());}};
 const {SOURCES}=await import('./model.mjs');
 for(const s of SOURCES){let data=s.id==='alerts'?parseAlerts(JSON.stringify({features:[alert]}),now):s.id==='radar'?{issuedAt:now.toISOString(),frames:[now.toISOString()]}:{issuedAt:now.toISOString()};map.set('https://rctv19.com/__weather_cache/v1/'+s.id,Response.json({id:s.id,lastAttempt:now.toISOString(),lastSuccess:now.toISOString(),error:null,data}));}
 let calls=0;await weatherFromCache(cache,'https://rctv19.com',now,async()=>{calls++;throw Error('Should be cached');},config);assert.equal(calls,0);
 const later=new Date(+now+61000);let result=await weatherFromCache(cache,'https://rctv19.com',later,async()=>{calls++;return new Response('unavailable',{status:503});},config);assert.equal(calls,1);assert.equal(result.sources.alerts.state,'delayed');assert.equal(result.sources.alerts.data.alerts.length,1);
 result=await weatherFromCache(cache,'https://rctv19.com',new Date(+later+61000),async()=>{calls++;return Response.json({features:[]});},config);assert.equal(calls,2);assert.equal(result.sources.alerts.state,'current');assert.equal(result.sources.alerts.data.alerts.length,0);
});
test('regular mode stops collection of storm-only NHC and Isaias news sources',async()=>{const {weatherFromCache}=await import('./cache.mjs');const urls=[];const cache={async match(){return null;},async put(){}};await weatherFromCache(cache,'https://rctv19.com',now,async url=>{urls.push(url);return new Response('unavailable',{status:503});},{...config,modeOverride:'regular'});assert.ok(urls.length>0);assert.ok(urls.every(url=>!url.includes('nhc.noaa.gov')&&!url.includes('tippahnews.com')));});
